=== ljbg/git-test/javase/src/order.dtd
<!ELEMENT Orders (Order*)>
        <!ELEMENT Order  (name,number,city,zip)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT number (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT zip (#PCDATA)>
        <!ATTLIST Order orderID CDATA #REQUIRED>
        <!ATTLIST Order orderDate CDATA #REQUIRED>

=== ljbg/git-test/javase/src/order.xml
<?xml version="1.0" encoding="utf-8"?>
<!--<!DOCTYPE Orders  SYSTEM "order.dtd">-->
<Orders xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="order.xsd">
    <Order orderID="A001" orderDate="2009-1-20">
        <name>玩具</name>
        <number>10</number>
        <city>北京</city>
        <zip>100000</zip>
    </Order>
    <Order orderID="A002" orderDate="2009-3-20">
        <name>文具</name>
        <number>10</number>
        <city>青岛</city>
        <zip>266000</zip>
    </Order>
</Orders>
